In [10]:
import cv2

cap = cv2.VideoCapture(1)
while True:
    _, frame = cap.read()
    frame_copy = frame.copy()
    hsv=cv2.cvtColor(frame_copy,cv2.COLOR_BGR2HSV)
    mask=cv2.inRange(hsv,(15,15,150),(28,25,255))
    whitened_image = cv2.bitwise_and(frame_copy,frame_copy, mask=mask)
    cv2.imshow("hsv",hsv)
    cv2.imshow("mask",mask)
    cv2.imshow("bgr",whitened_image)
    
    if cv2.waitKey(1) & 0xFF == 27:
        break
cv2.destroyAllWindows()

OpenCV: out device of bound (0-0): 1
OpenCV: camera failed to properly initialize!


AttributeError: 'NoneType' object has no attribute 'copy'

In [ ]:
import cv2
import numpy as np

cap = cv2.VideoCapture(1)
while True:
    _, frame = cap.read()
    frame_copy = frame.copy()
    hsv = cv2.cvtColor(frame_copy, cv2.COLOR_BGR2HSV)
    mask = cv2.inRange(hsv, (15, 15, 50), (28, 25, 300))

    # Tạo ảnh trắng có cùng kích thước với frame
    white_image = np.ones_like(frame) * 255

    # Áp dụng mask: các điểm ảnh trong mask được tô trắng
    result_image = cv2.bitwise_or(white_image, white_image, mask=mask)

    cv2.imshow("HSV", hsv)
    cv2.imshow("Mask", mask)
    cv2.imshow("Result", result_image)
    
    if cv2.waitKey(1) & 0xFF == 27:
        break

cv2.destroyAllWindows()


2024-05-05 22:13:52.966 Python[15119:788643] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
2024-05-05 22:13:53.299 Python[15119:788643] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.


In [1]:
import cv2
import pandas as pd
import numpy as np
paper=[]

def get_hsv_values(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        hsv_value = hsv_image[y, x]
        paper.append(hsv_value)
        print("HSV value at point ({}, {}): {}".format(x, y, hsv_value))

# Khởi tạo camera
cap = cv2.VideoCapture(1)

# Thiết lập sự kiện cho việc nhấp chuột
cv2.namedWindow('Camera Feed')
cv2.setMouseCallback('Camera Feed', get_hsv_values)

while True:
    # Đọc frame từ camera
    ret, frame = cap.read()

    # Chuyển đổi frame từ không gian màu BGR sang HSV
    hsv_image = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    mask=cv2.inRange(hsv_image,(15,5,150),(28,55,255))
    # Hiển thị frame
    cv2.imshow('Camera Feed', frame)
    cv2.imshow('masked', mask)
    # Thoát vòng lặp nếu nhấn phím 'q'
    if cv2.waitKey(1) & 0xFF == ord('q'):
        # paper.to_csv("/Users/mac/Dev/Computer_Vision/Computer-Vision/outputs/HSV/paper.csv")
        break

# Giải phóng camera và đóng cửa sổ
cap.release()
cv2.destroyAllWindows()


2024-05-05 22:20:28.180 Python[15228:795276] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
2024-05-05 22:20:29.973 Python[15228:795276] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.


HSV value at point (1679, 11): [ 15 114 185]


In [ ]:
paper

[array([ 21,  27, 230], dtype=uint8),
 array([ 23,  26, 229], dtype=uint8),
 array([ 21,  27, 230], dtype=uint8),
 array([ 20,  23, 230], dtype=uint8),
 array([ 18,  30, 222], dtype=uint8),
 array([ 23,  26, 229], dtype=uint8),
 array([ 23,  22, 230], dtype=uint8),
 array([ 23,  22, 230], dtype=uint8),
 array([ 20,  26, 232], dtype=uint8),
 array([ 18,  27, 223], dtype=uint8),
 array([ 18,  30, 223], dtype=uint8),
 array([ 17,  32, 224], dtype=uint8),
 array([ 18,  30, 223], dtype=uint8),
 array([ 21,  26, 233], dtype=uint8),
 array([ 21,  26, 233], dtype=uint8),
 array([ 20,  30, 240], dtype=uint8),
 array([ 21,  32, 237], dtype=uint8),
 array([ 20,  30, 237], dtype=uint8),
 array([ 20,  30, 240], dtype=uint8),
 array([ 21,  32, 237], dtype=uint8),
 array([ 21,  33, 233], dtype=uint8),
 array([ 20,  29, 232], dtype=uint8),
 array([ 21,  26, 233], dtype=uint8),
 array([ 20,  28, 239], dtype=uint8),
 array([ 19,  27, 240], dtype=uint8),
 array([ 19,  30, 242], dtype=uint8),
 array([ 21,